name: Build and Push Docker Image

on:
  push:
    branches:
      - main 
      - develop 
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file from secret
        run: echo "${{ secrets.PROD_ENV }}" > .env

      - name: Replace baseUrl in config.dart for production
        run: |
          sed -i "s|http://localhost:9000|https://ea2-api.upc.edu|g" lib/config.dart

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: jthort00/skynet-frontend:latest
